services:
  - type: web
    name: anshih
    env: node
    region: oregon
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    healthCheckPath: /api/media
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: CLIENT_URL
        sync: false
      - key: UPLOADTHING_TOKEN
        sync: false
      - key: UPLOADTHING_SECRET
        sync: false
